// Source: "The Arcana Codex" — Harmeet's personal tarot reference PDF.
// Keyed by exact card name (matches src/lib/tarot.js DECK names).
// Used to ground ORACLE readings (spreads + photo-scan) in this specific text
// instead of the model's generic training-data knowledge of tarot.

export const CODEX = {
  // ---------------- MAJOR ARCANA ----------------
  'The Fool': `Planet: Uranus | Chakra: Crown. PHYSICAL: Restlessness, nervous excitement, difficulty grounding. CAREER: New job, startup, career change. LOVE: New relationship, fresh start. SPIRITUAL: Trust the unknown. SHADOW: Fear disguised as impulsiveness. HEALING: Take one small leap of faith toward a goal.`,
  'The Magician': `Planet: Mercury | Chakra: Solar Plexus. PHYSICAL: Mental overstimulation, digestive tension. CAREER: Business, sales, communication, leadership. LOVE: Taking initiative in love. SPIRITUAL: You already possess the tools you need. SHADOW: Manipulation, ego, control. HEALING: List your strengths and use one consciously.`,
  'The High Priestess': `Planet: Moon | Chakra: Third Eye. PHYSICAL: Sleep issues, hormonal fluctuations, headaches. CAREER: Research, counseling, healing professions. LOVE: Hidden feelings, intuitive connection. SPIRITUAL: Trust inner wisdom. SHADOW: Avoidance, secrecy. HEALING: Spend 15 minutes daily in silence.`,
  'The Empress': `Planet: Venus | Chakra: Sacral. PHYSICAL: Hormonal imbalance, fertility concerns, emotional eating. CAREER: Creative work, beauty industry, nurturing professions. LOVE: Deep affection and emotional fulfillment. SPIRITUAL: Receive abundance. SHADOW: Over-giving and self-neglect. HEALING: Practice receiving without guilt.`,
  'The Emperor': `Zodiac: Aries | Chakra: Root. PHYSICAL: Back tension, stiffness, stress from responsibility. CAREER: Management, authority, entrepreneurship. LOVE: Need for stability and commitment. SPIRITUAL: Create healthy structure. SHADOW: Control issues. HEALING: Delegate one responsibility.`,
  'The Hierophant': `Zodiac: Taurus | Chakra: Throat. PHYSICAL: Throat issues, neck stiffness. CAREER: Teaching, mentoring, spiritual work. LOVE: Traditional commitment and marriage. SPIRITUAL: Seek wisdom and guidance. SHADOW: Rigid beliefs. HEALING: Question one limiting belief.`,
  'The Lovers': `Zodiac: Gemini | Chakra: Heart. PHYSICAL: Heart-centered stress, nervous energy. CAREER: Partnerships and collaborations. LOVE: Soul connections and important choices. SPIRITUAL: Choose alignment over fear. SHADOW: People-pleasing and codependency. HEALING: Make one decision based on your truth.`,
  'The Chariot': `Zodiac: Cancer | Chakra: Solar Plexus. PHYSICAL: Stomach tension, stress-related digestion. CAREER: Victory, promotion, achievement. LOVE: Moving relationship forward. SPIRITUAL: Master opposing forces within. SHADOW: Forcing outcomes. HEALING: Practice patience before action.`,
  'Strength': `Zodiac: Leo | Chakra: Solar Plexus. PHYSICAL: Fatigue from emotional suppression. CAREER: Leadership through influence. LOVE: Compassion and emotional maturity. SPIRITUAL: Gentleness is power. SHADOW: Self-doubt. HEALING: Acknowledge one personal strength daily.`,
  'The Hermit': `Zodiac: Virgo | Chakra: Third Eye. PHYSICAL: Fatigue, isolation-related stress. CAREER: Research, healing, spiritual guidance. LOVE: Need for personal space. SPIRITUAL: Seek inner truth. SHADOW: Isolation and withdrawal. HEALING: Journal your inner wisdom.`,
  'Wheel of Fortune': `Planet: Jupiter | Chakra: Crown. PHYSICAL: Stress from uncertainty. CAREER: Lucky opportunities and expansion. LOVE: Fated connections. SPIRITUAL: Trust divine timing. SHADOW: Resistance to change. HEALING: Practice accepting uncertainty.`,
  'Justice': `Zodiac: Libra | Chakra: Throat. PHYSICAL: Jaw tension, throat tightness. CAREER: Law, administration, contracts. LOVE: Honest communication. SPIRITUAL: Cause and effect. SHADOW: Judgment and blame. HEALING: Take responsibility for one situation.`,
  'The Hanged Man': `Planet: Neptune | Chakra: Crown. PHYSICAL: Fatigue, low energy, feeling stuck. CAREER: Necessary delays. LOVE: Pause for reflection. SPIRITUAL: Surrender creates wisdom. SHADOW: Victim mentality. HEALING: Release the need to control outcomes.`,
  'Death': `Zodiac: Scorpio | Chakra: Root. PHYSICAL: Detox symptoms, emotional exhaustion. CAREER: Major career transformation. LOVE: Endings leading to growth. SPIRITUAL: Rebirth follows endings. SHADOW: Fear of change. HEALING: Release one thing that no longer serves you.`,
  'Temperance': `Zodiac: Sagittarius | Chakra: Sacral. PHYSICAL: Body seeking balance and recovery. CAREER: Steady progress. LOVE: Harmony and healing. SPIRITUAL: Balance creates healing. SHADOW: Excess and impatience. HEALING: Create balance in one area of life.`,
  'The Devil': `Zodiac: Capricorn | Chakra: Root. PHYSICAL: Addiction patterns, chronic tension. CAREER: Material ambition. LOVE: Toxic attachments. SPIRITUAL: Awareness creates freedom. SHADOW: Fear, obsession, attachment. HEALING: Identify and release one unhealthy habit.`,
  'The Tower': `Planet: Mars | Chakra: Root. PHYSICAL: Sudden stress responses, nervous system overload. CAREER: Unexpected changes. LOVE: Sudden revelations. SPIRITUAL: Truth destroys illusion. SHADOW: Resistance to transformation. HEALING: Write down what needs to end.`,
  'The Star': `Zodiac: Aquarius | Chakra: Heart. PHYSICAL: Healing, recovery, improved vitality. CAREER: Creative and healing professions. LOVE: Hope after heartbreak. SPIRITUAL: Faith and renewal. SHADOW: Hopelessness. HEALING: Practice gratitude daily.`,
  'The Moon': `Zodiac: Pisces | Chakra: Third Eye. PHYSICAL: Anxiety, vivid dreams, emotional overwhelm. CAREER: Creative and intuitive work. LOVE: Uncertainty and hidden emotions. SPIRITUAL: Trust intuition over fear. SHADOW: Illusion and confusion. HEALING: Keep a dream journal.`,
  'The Sun': `Planet: Sun | Chakra: Solar Plexus. PHYSICAL: High vitality and energy. CAREER: Recognition, success, promotion. LOVE: Joyful and honest relationship. SPIRITUAL: Express your authentic self. SHADOW: Ego and arrogance. HEALING: Celebrate your achievements.`,
  'Judgement': `Planet: Pluto | Chakra: Throat. PHYSICAL: Emotional release, throat tension. CAREER: Life calling and purpose work. LOVE: Relationship renewal. SPIRITUAL: Answer the soul's calling. SHADOW: Guilt and self-criticism. HEALING: Write a forgiveness letter to yourself.`,
  'The World': `Planet: Saturn | Chakra: Crown. PHYSICAL: Completion of healing cycles. CAREER: Achievement, mastery, expansion. LOVE: Long-term commitment. SPIRITUAL: Completion and fulfillment. SHADOW: Fear of beginning again. HEALING: Celebrate one achievement before chasing the next goal.`,

  // ---------------- WANDS (Fire) ----------------
  'Ace of Wands': `The Spark — a new idea, relationship, opportunity, or passion enters your life; pure fire energy before form; "Will you act?" LOVE: new romantic connection, passion reignites, strong attraction. CAREER: new job/business venture/creative launch. FINANCE: new income source. TIMING: 1 day to 1 month; strong in Aries/Leo/Sagittarius seasons. SPIRITUAL: psychic awakening, kundalini activation. MEDICAL: increased vitality; watch fever, inflammation, headaches, adrenal fatigue. PERSON: passionate, entrepreneurial, charismatic. SHADOW: burnout, impulsiveness, lack of follow-through. Mantra: "I desire."`,
  'Two of Wands': `The Vision — the dream becomes a plan; "How far can I go?" LOVE: long-distance, planning a future, choosing between two options. CAREER: business expansion, strategic planning. FINANCE: investment planning. TIMING: 2 weeks to 2 months. MEDICAL: stress headaches, mental fatigue, blood pressure fluctuation. PERSON: visionary, strategic. SHADOW: fear of action, analysis paralysis. Mantra: "I envision."`,
  'Three of Wands': `The Expansion — decisions made, now waiting for results; trust what you cannot yet see. LOVE: relationship moves forward, overseas connection. CAREER: business growth, international success. FINANCE: investments begin producing returns. TIMING: 3 weeks to 3 months. MEDICAL: recovery phase. PERSON: explorer, forward-looking. SHADOW: delays, unrealistic expectations. Mantra: "I expand."`,
  'Four of Wands': `The First Success — a milestone, celebration, stability; growth is not finished. LOVE: engagement, marriage, moving in together. CAREER: milestone completion. FINANCE: property purchase, stable phase. TIMING: 4 weeks to 4 months. MEDICAL: recovery, stable conditions. PERSON: loyal, family-oriented. SHADOW: delayed celebrations, family disagreements. Mantra: "I celebrate."`,
  'Five of Wands': `The Challenge — competition, jealousy, self-doubt; strength develops through opposition. LOVE: arguments, power struggles, third-party interference. CAREER: workplace competition, office politics. FINANCE: disputes. TIMING: immediate to 5 weeks. MEDICAL: stress, anxiety, inflammation. PERSON: competitive, restless. SHADOW: drama, ego clashes. Mantra: "I struggle."`,
  'Six of Wands': `The Victory — public success, recognition; "Am I doing this for purpose or praise?" LOVE: relationship becomes public, admiration. CAREER: promotion, awards. FINANCE: breakthrough, increased income. TIMING: 6 weeks to 6 months. MEDICAL: recovery, improved vitality. PERSON: confident, popular. SHADOW: arrogance, dependence on validation. Mantra: "I succeed."`,
  'Seven of Wands': `The Defense — leadership is staying at the top, not reaching it. LOVE: defending the relationship, setting boundaries. CAREER: protecting your position, competition. FINANCE: protecting assets, caution needed. TIMING: 7 weeks to 7 months. SPIRITUAL: psychic protection, resilience. MEDICAL: immune activation; watch chronic stress, cortisol, blood pressure. PERSON: determined, protective. SHADOW: defensiveness, paranoia. Mantra: "I defend."`,
  'Eight of Wands': `The Acceleration — momentum increases rapidly, "you are finally aligned." LOVE: fast-moving romance, important messages. CAREER: job offer, growth accelerates. FINANCE: fast movement, money incoming. TIMING: 8 days to 8 weeks — one of the fastest cards. SPIRITUAL: rapid manifestation, synchronicities. MEDICAL: quick recovery; watch nervous overload, anxiety, insomnia. PERSON: energetic, fast-paced. SHADOW: rushing, poor planning. Mantra: "I accelerate."`,
  'Nine of Wands': `The Warrior — tired but still standing; the final test before completion. LOVE: emotional walls, healing from past heartbreak, relationship tested but survives. CAREER: nearing completion, work fatigue. FINANCE: temporary pressure, need discipline. TIMING: 9 weeks to 9 months. SPIRITUAL: spiritual warrior energy, karmic lessons nearing completion. MEDICAL: chronic fatigue; watch burnout, sleep disturbance. PERSON: survivor, strong-willed. SHADOW: hypervigilance, trust issues. Mantra: "I endure."`,
  'Ten of Wands': `The Burden — success has weight; every blessing carries responsibility. LOVE: one partner carrying the relationship, burdens increase. CAREER: heavy workload, leadership responsibility. FINANCE: obligations, debt repayment. TIMING: 10 weeks to 10 months. SPIRITUAL: karmic burdens releasing, need to surrender control. MEDICAL: back/neck/shoulder tension; watch burnout. PERSON: responsible, burdened. SHADOW: overwhelm, martyr complex, refusing help. Mantra: "I carry." True mastery is learning to carry success without losing yourself.`,
  'Page of Wands': `Adventure, curiosity, enthusiasm, exciting news. LOVE: flirty communication, new admirer. CAREER: new opportunity, learning phase. FINANCE: new ideas, side hustle. TIMING: days to weeks. SPIRITUAL: beginning a spiritual journey. MEDICAL: increased vitality; watch hyperactivity, restlessness. PERSON: youthful, adventurous. SHADOW: immaturity, lack of commitment.`,
  'Knight of Wands': `Action, adventure, fearless pursuit. LOVE: passionate affair, sudden developments. CAREER: advancement, entrepreneurial action, relocation. FINANCE: risk-taking, rapid changes. TIMING: days to 3 months. SPIRITUAL: powerful manifestation energy, spiritual courage. MEDICAL: strong vitality; watch injuries from haste. PERSON: bold, charismatic. SHADOW: impulsiveness, recklessness.`,
  'Queen of Wands': `Confidence, magnetism, leadership, charisma. LOVE: being admired/pursued, strong feminine energy. CAREER: leadership role, personal brand growth. FINANCE: expansion via visibility. TIMING: 1–3 months, strongest in Leo season. SPIRITUAL: strengthened intuition, psychic development. MEDICAL: hormonal balance improving; watch hormonal imbalance/PCOS tendencies. PERSON: attractive, confident, influential. SHADOW: jealousy, ego-driven decisions, attention-seeking.`,
  'King of Wands': `Mastery, leadership, vision, entrepreneurship. LOVE: mature passionate partner, strong masculine energy. CAREER: business success, executive leadership. FINANCE: wealth through leadership. TIMING: 3 months to 1 year, strong Aries/Leo/Sagittarius. SPIRITUAL: spiritual teacher, master manifestor. MEDICAL: strong recovery potential; watch high blood pressure, burnout from leadership stress. PERSON: influential, visionary. SHADOW: dominance, arrogance, control issues.`,

  // ---------------- CUPS (Water) ----------------
  'Ace of Cups': `The Birth of Emotion — the heart opens to love, intuition, healing, spiritual guidance. Timing: 1 day–1 month; water seasons Cancer/Scorpio/Pisces. Professions: Healer, Counselor, Tarot Reader, Therapist, Artist. Shadow: emotional overwhelm, over-sensitivity, fear of vulnerability, dependency. Lesson: open your heart without losing yourself. Meaning: new love, emotional beginnings, healing, intuition, spiritual blessings.`,
  'Two of Cups': `The Mirror — connection through another person; relationships reveal who we truly are. Timing: 2 weeks–2 months. Professions: Marriage Counselor, Relationship Coach, Negotiator. Shadow: codependency, attachment, obsession, losing identity. Meaning: partnership, attraction, soul connection, mutual respect, reconciliation.`,
  'Three of Cups': `The Tribe — the heart expands into friendship, support, community; joy grows when shared. Timing: 3 weeks–3 months. Professions: Event Planner, Community Builder, Hospitality. Shadow: gossip, third-party interference, over-socialization. Meaning: friendship, celebration, community, social gatherings.`,
  'Four of Cups': `Emotional Stagnation — dissatisfaction, disconnection; gratitude awakens the heart. Timing: 4 weeks–4 months. Professions: Researcher, Writer, Monk, Meditation Teacher. Shadow: apathy, emotional numbness, depression, missed opportunities. Meaning: emotional boredom, contemplation, introspection.`,
  'Five of Cups': `The Heartbreak — grief and disappointment; every ending creates space for a new beginning. Timing: immediate–5 months. Professions: Grief Counselor, Trauma Therapist, Energy Healer. Shadow: victim mentality, regret, bitterness, isolation. Meaning: loss, grief, disappointment, focusing on what's been lost.`,
  'Six of Cups': `The Inner Child — reconnecting with innocence and emotional healing; heal the past but don't live there. Timing: 6 weeks–6 months. Professions: Child Therapist, Teacher, Family Counselor. Shadow: living in the past, nostalgia, escapism. Meaning: nostalgia, childhood memories, innocence, past connections.`,
  'Seven of Cups': `The Illusion — lost among possibilities and fantasies; discernment is spiritual maturity. Timing: 7 weeks–7 months. Professions: Filmmaker, Artist, Actor, Visionary Entrepreneur. Shadow: confusion, delusion, fantasy addiction, poor choices. Meaning: choices, illusions, fantasies, opportunities, confusion.`,
  'Eight of Cups': `The Departure — leaving behind what no longer fulfills; growth requires letting go. Timing: 8 weeks–8 months. Professions: Spiritual Teacher, Pilgrim, Life Coach, Retreat Facilitator. Shadow: avoidance, running away, fear of commitment. Meaning: walking away, emotional detachment, seeking deeper fulfillment.`,
  'Nine of Cups': `The Wish Fulfilled — self-love and emotional abundance; happiness begins within. Timing: 9 weeks–9 months. Professions: Luxury Industry, Influencer, Personal Brand Creator. Shadow: self-indulgence, arrogance, complacency, excess. Meaning: wish fulfillment, satisfaction, self-love, gratitude. Mantra: "I can make myself happy."`,
  'Ten of Cups': `Emotional Heaven — emotional fulfillment and harmony; true abundance is shared love. Timing: 10 weeks–10 months. Professions: Family Counselor, Relationship Coach, Spiritual Mentor. Shadow: unrealistic expectations, emotional dependency on family, perfectionism. Meaning: emotional happiness, family harmony, lasting love. Mantra: "I can share happiness with others."`,
  'Page of Cups': `The Emotional Student — new cycle through curiosity and emotional openness. Timing: days–weeks. Professions: Student, Artist, Tarot Reader, Writer, Musician. Shadow: emotional immaturity, naivety, daydreaming, lack of boundaries. Meaning: emotional messages, intuition, creativity, new feelings.`,
  'Knight of Cups': `The Romantic Seeker — follows dreams and heart's desires; dreams require action and grounding. Timing: 1 week–3 months. Professions: Poet, Musician, Actor, Motivational Speaker. Shadow: unrealistic expectations, emotional inconsistency, love addiction. Meaning: romance, charm, emotional pursuit, idealism.`,
  'Queen of Cups': `The Emotional Healer — masters intuition, compassion, emotional awareness; feel deeply but remain centered. Timing: 1–3 months, strong Cancer season. Professions: Psychic, Healer, Therapist, Medium, Nurse. Shadow: absorbing others' pain, emotional exhaustion, poor boundaries, martyrdom. Meaning: compassion, intuition, empathy, healing, psychic awareness. Mantra: "I understand emotions."`,
  'King of Cups': `The Master of the Heart — emotionally mature and spiritually balanced after love, loss, grief, healing. Timing: 3 months–1 year. Professions: Therapist, Judge, Spiritual Teacher, emotionally intelligent CEO, Mentor. Shadow: emotional suppression, manipulation, passive control, hidden emotions. Meaning: emotional mastery, wisdom, balance, mature love, self-control. Mantra: "I have mastered them." Lesson: emotional mastery is remaining calm while emotions flow through you, not controlling them.`,

  // ---------------- SWORDS (Air) ----------------
  'Ace of Swords': `Truth Appears — mental clarity, breakthrough, new ideas; truth liberates. CAREER: new idea, contract, interview, decision. LOVE: honest conversation, truth revealed. HEALTH: mental clarity, diagnosis, treatment begins. TIMING: days to weeks. SHADOW: harsh words, coldness. LESSON: truth sets you free.`,
  'Two of Swords': `Truth is Avoided — indecision, stalemate, blocked emotions to maintain peace. CAREER: delayed decision. LOVE: emotional blockage. HEALTH: stress-related symptoms. TIMING: 2 weeks–2 months. SHADOW: denial. LESSON: avoidance is also a decision; choose rather than avoid.`,
  'Three of Swords': `Truth Hurts — heartbreak, painful truth, necessary growth. CAREER: rejection or setback. LOVE: separation, painful truth. HEALTH: emotional stress affecting body. TIMING: 3 weeks–3 months. SHADOW: bitterness. LESSON: pain reveals what must heal; healing follows pain.`,
  'Four of Swords': `Truth is Processed — rest, recovery, reflection after heartbreak. CAREER: career pause. LOVE: need for space. HEALTH: recovery period. TIMING: 4 weeks–4 months. SHADOW: withdrawal, isolation, stagnation. LESSON: healing requires rest; rest is productive.`,
  'Five of Swords': `Truth Creates Conflict — ego battles, hollow victories; not every battle is worth fighting. CAREER: office politics. LOVE: arguments, power struggles. HEALTH: stress, tension. TIMING: 5 weeks–5 months. SHADOW: manipulation, resentment. LESSON: winning isn't everything.`,
  'Six of Swords': `Truth Leads to Growth — transition, moving forward, choosing peace over conflict. CAREER: new job or relocation. LOVE: moving beyond difficulties. HEALTH: gradual improvement. TIMING: 6 weeks–6 months. SHADOW: carrying emotional baggage forward, difficulty letting go. LESSON: growth often requires leaving the familiar.`,
  'Seven of Swords': `Truth is Tested — strategy, independence, hidden motives; intelligence must be used wisely. CAREER: independent work. LOVE: hidden motives, secrecy. HEALTH: need for second opinions. TIMING: 7 weeks–7 months. SHADOW: deception, self-deception. LESSON: integrity matters as much as intelligence.`,
  'Eight of Swords': `Truth Reveals Self-Imposed Limits — mental imprisonment, the mind as the prison. CAREER: feeling stuck professionally. LOVE: fear-based patterns. HEALTH: anxiety, overthinking. TIMING: 8 weeks–8 months. SHADOW: victim mentality, anxiety, helplessness. LESSON: most chains are mental.`,
  'Nine of Swords': `Truth Confronts Fear — worry, guilt, sleepless nights; the mind becomes its own tormentor. CAREER: career anxiety. LOVE: guilt and emotional distress. HEALTH: insomnia, stress. TIMING: 9 weeks–9 months. SHADOW: obsession, catastrophic thinking. LESSON: fear grows in darkness but weakens in awareness; most fears never materialize.`,
  'Ten of Swords': `Truth Ends the Illusion — ending, surrender, transformation; the worst is over, dawn appears. CAREER: job ending or major change. LOVE: final breakup or closure. HEALTH: recovery after crisis. TIMING: 10 weeks–10 months. SHADOW: resistance to necessary change. LESSON: every ending contains a new beginning.`,
  'Page of Swords': `Curiosity, messages, learning. CAREER: student, researcher, trainee. LOVE: watching from afar, new conversations. HEALTH: seeking information. TIMING: news arriving soon. PERSONALITY: curious, observant, intelligent. SHADOW: gossip, immaturity. LESSON: stay curious.`,
  'Knight of Swords': `Action, speed, ambition. CAREER: rapid advancement. LOVE: fast-moving romance. HEALTH: sudden improvement or flare-up. TIMING: days to weeks. PERSONALITY: bold, driven, direct. SHADOW: recklessness. LESSON: think before acting.`,
  'Queen of Swords': `Wisdom, independence, discernment. CAREER: advisor, lawyer, strategist. LOVE: honest, mature communication. HEALTH: clear diagnosis. TIMING: a mature woman influences events. PERSONALITY: intelligent, perceptive. SHADOW: emotional detachment. LESSON: compassion and truth can coexist.`,
  'King of Swords': `Authority, mastery of intellect. CAREER: executive, judge, leader, consultant. LOVE: mature, logical partner. HEALTH: expert medical guidance. TIMING: an influential authority figure appears. PERSONALITY: strategic, disciplined, objective. SHADOW: control, rigidity. LESSON: wisdom requires fairness. Core lesson of Swords: the greatest battle is never with others — it is with one's own thoughts.`,

  // ---------------- PENTACLES (Earth) ----------------
  'Ace of Pentacles': `The Seed — a new opportunity, a doorway to prosperity, growth, or healing. Lesson: recognize and nurture the seed before expecting results.`,
  'Two of Pentacles': `The Balance — responsibilities increase, priorities compete, adaptation needed. Lesson: flexibility and balance amidst constant change.`,
  'Three of Pentacles': `The Builder — skills develop through effort and collaboration; mentors and teamwork transform potential into progress. Lesson: mastery requires practice and support.`,
  'Four of Pentacles': `The Protector — success creates a desire for security; fear of loss may cause control or resistance to change. Lesson: the difference between healthy boundaries and limitation.`,
  'Five of Pentacles': `The Exile — struggle, scarcity, rejection, insecurity; hardship is temporary and does not determine your value. Lesson: faith during difficult times.`,
  'Six of Pentacles': `The Exchange — support arrives, resources flow again through giving and receiving. Lesson: abundance thrives through balanced exchange.`,
  'Seven of Pentacles': `The Gardener — growth is occurring but not yet fully visible; patience is necessary. Lesson: trust the process and divine timing.`,
  'Eight of Pentacles': `The Apprentice — dedication, repetition, and discipline create excellence. Lesson: mastery is built one small step at a time.`,
  'Nine of Pentacles': `The Independent Soul — rewards of hard work appear; confidence, self-sufficiency, fulfillment emerge. Lesson: discovering your own value independent of others.`,
  'Ten of Pentacles': `The Legacy — material and emotional security established, strong enough to benefit future generations. Lesson: creating something that lasts beyond yourself.`,
  'Page of Pentacles': `The Student — a new level of learning begins; curiosity and openness create future opportunities. Lesson: remain teachable.`,
  'Knight of Pentacles': `The Worker — steady effort replaces excitement; progress through consistency and responsibility. Lesson: perseverance and commitment.`,
  'Queen of Pentacles': `The Nurturer — abundance cultivated with care, wisdom, and practicality. Lesson: nurture yourself and others without sacrificing stability.`,
  'King of Pentacles': `The Master Manifestor — material success matched by wisdom, responsibility, leadership. Lesson: true wealth includes integrity, generosity, and purpose.`,
}

// General framework text (timing rules, suit temperament) — included once per reading
// as shared context, not per-card, to ground interpretive tone without repeating for every card.
export const CODEX_FRAMEWORK = `Timing framework from the user's own reference (use only if timing is relevant to the question):
Wands (Fire) = fastest, days to weeks. Cups (Water) = weeks to months, emotional unfolding. Swords (Air) = days to months, sudden but often delayed by indecision. Pentacles (Earth) = slowest, months to years. Court cards: Page = days–weeks, Knight = weeks–months, Queen = 1–6 months, King = 3 months–1 year+. Major Arcana: Magician/Chariot/Wheel of Fortune/Sun/Judgement = days–weeks (quick); High Priestess/Empress/Lovers/Strength/Temperance/Star = weeks–months (medium); Hermit/Hanged Man/Death/Devil/Tower/Moon/World = months–years (long-term).
When reading Major Arcana, consider: which chakra is seeking attention, what shadow pattern is active, what spiritual lesson is being taught, what area of life is transforming, what healing action is required.`

export function codexFor(cardName) {
  return CODEX[cardName] || null
}
